#ifndef __MonkeyMainFrame__
#define __MonkeyMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "Monkey.h"

//// end generated include

/** Implementing MainFrame */
class MonkeyMainFrame : public MainFrame
{
	public:
		/** Constructor */
		MonkeyMainFrame( wxWindow* parent );
	//// end generated class members








};

#endif // __MonkeyMainFrame__
